name: Bot build script

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check_symlinks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Git clone software-layer
        run: git clone https://github.com/EESSI/software-layer.git

      - name: Run symlink commands
        run: |
          set -e

          for file in $(ls software-layer | egrep -v 'easystacks|LICENSE|README.md|^bot'); do
              ln -s software-layer/${file}
          done

          for file in $(ls software-layer/bot | grep -v '^build.sh'); do
              ln -s ../software-layer/bot/${file} bot/${file}
          done
