# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests for consistency of README.md
on:
  push:
    paths:
      - README.md
      - init/eessi_defaults

  pull_request:
    branches:
      - main
    paths:
      - README.md
      - init/eessi_defaults
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: verify if README.md is consistent with EESSI_PILOT_VERSION from init/eessi_defaults
      run: |
        source init/eessi_defaults
        grep "${EESSI_PILOT_VERSION}" README.md

    - name: verify if README.md is consistent with EESSI_CVMFS_REPO from init/eessi_defaults
      run: |
        source init/eessi_defaults
        grep "${EESSI_CVMFS_REPO}" README.md
