# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests for eessi_archdetect.sh
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        proc_cpuinfo:
          - x86_64/intel/haswell
          - x86_64/intel/skylake_avx512
          - x86_64/amd/zen2/Azure-CentOS7-7V12
          - x86_64/amd/zen3
          - ppc64le/power9le
            # - aarch64/graviton2
            # - aarch64/graviton3
          - aarch64/arm/neoverse-n1
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: test eessi_archdetect.sh
      run: |
          export EESSI_MACHINE_TYPE=${{matrix.proc_cpuinfo}}
          export EESSI_MACHINE_TYPE=${EESSI_MACHINE_TYPE%%/*}
          export EESSI_PROC_CPUINFO=./tests/archdetect/${{matrix.proc_cpuinfo}}.cpuinfo
          #CPU_ARCH=$(./init/eessi_archdetect.sh cpupath)
          CPU_ARCH=$(./init/arch_detect.sh cpupath)
          if [[ $CPU_ARCH == "$( cat ${{matrix.proc_cpuinfo}}.output )" ]]; then
              echo "Test for ${{matrix.proc_cpuinfo}} PASSED: $CPU_ARCH" >&2
          else
              echo "Test for ${{matrix.proc_cpuinfo}} FAILED: $CPU_ARCH" >&2
              exit 1
          fi
