# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests for eessi_container.sh script
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  eessi_container_script:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        SCRIPT_ARGS:
        - "--help"
        - "--info"
    steps:
        - name: Check out software-layer repository
          uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

        - name: Mount EESSI CernVM-FS pilot repository
          uses: eessi/github-action-eessi@v2

        - name: install Apptainer
          run: |
            ./install_apptainer_ubuntu.sh

        - name: Test eessi_container.sh script
          run: |
              ./eessi_container.sh ${{matrix.SCRIPT_ARGS}}
